# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 464)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 101, 21))
        self.label_2.setObjectName("label_2")
        self.boxUsuariosRanking = QtWidgets.QComboBox(self.centralwidget)
        self.boxUsuariosRanking.setGeometry(QtCore.QRect(180, 70, 69, 22))
        self.boxUsuariosRanking.setObjectName("boxUsuariosRanking")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 150, 111, 21))
        self.label_4.setObjectName("label_4")
        self.btnRecomendar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecomendar.setGeometry(QtCore.QRect(180, 200, 75, 23))
        self.btnRecomendar.setStyleSheet("")
        self.btnRecomendar.setObjectName("btnRecomendar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 60, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 100, 141, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 220, 61, 21))
        self.label_8.setObjectName("label_8")
        self.boxUsuarioPrediccion = QtWidgets.QComboBox(self.centralwidget)
        self.boxUsuarioPrediccion.setGeometry(QtCore.QRect(570, 60, 69, 22))
        self.boxUsuarioPrediccion.setObjectName("boxUsuarioPrediccion")
        self.boxPliculas = QtWidgets.QComboBox(self.centralwidget)
        self.boxPliculas.setGeometry(QtCore.QRect(570, 100, 151, 22))
        self.boxPliculas.setObjectName("boxPliculas")
        self.btnPredecir = QtWidgets.QPushButton(self.centralwidget)
        self.btnPredecir.setGeometry(QtCore.QRect(410, 140, 75, 23))
        self.btnPredecir.setStyleSheet("")
        self.btnPredecir.setObjectName("btnPredecir")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 250, 211, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.textRanking = QtWidgets.QLineEdit(self.centralwidget)
        self.textRanking.setGeometry(QtCore.QRect(180, 110, 41, 20))
        self.textRanking.setObjectName("textRanking")
        self.textSimilitud = QtWidgets.QLineEdit(self.centralwidget)
        self.textSimilitud.setGeometry(QtCore.QRect(180, 150, 41, 20))
        self.textSimilitud.setObjectName("textSimilitud")
        self.textPrediccion = QtWidgets.QLineEdit(self.centralwidget)
        self.textPrediccion.setGeometry(QtCore.QRect(470, 220, 61, 20))
        self.textPrediccion.setObjectName("textPrediccion")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mi Recomendador"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Recomendaciones</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Items del ranking</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Selecciona un usuario:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Umbral de similitud:</span></p></body></html>"))
        self.btnRecomendar.setText(_translate("MainWindow", "!Recomendar!"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Ranking:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Selecciona un usuario:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Selecciona una película:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Predicción:</span></p></body></html>"))
        self.btnPredecir.setText(_translate("MainWindow", "!Predecir!"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pelicula"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Predicción"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
